//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZaghiniAdmin.Models
{

    public partial class sectionitem
    {
        public int id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public bool active { get; set; }
        public bool onlyregistercanread { get; set; }
        public int idsection { get; set; }
        public string image { get; set; }
    
        public virtual section section { get; set; }
    }
}
